<?php if (!empty($effects)) {
    $cr_effect = ' cr-animate-gen"  data-gen="'.$effects.'" data-gen-offset="bottom-in-view';
} else {
    $cr_effect ='';
}

# Addition CSS styles
$addition_css_styles = '';

if (!empty($css_styles)) {
	$addition_css_styles .= $css_styles;
}
if (!empty($addition_css_styles)) {
	$addition_css_styles = 'style="' . $addition_css_styles . '"';
}

?>

<div class="clients_module module row <?php echo (!empty($css)) ? $css : ''; ?> <?php echo $cr_effect; ?>"  <?php echo $addition_css_styles; ?>>

    <?php if (!empty($r_items)): ?>

        <div class="clients-list nine columns">
            <div class="row">
                <div class="clients-list-wrap twelve columns centered" id="<?php echo (!empty($unique_id)) ? $unique_id : ''; ?>">
                    <ul class="clients-list-slider">

                        <?php

                        foreach ($r_items as $item):

                            if (isset($item['image'])) :

                                $img_url = wp_get_attachment_url($item['image']);

                                $article_image = aq_resize($img_url, 186, 186, true); //resize & crop img
                                ?>

                                <li class="clients-item">

                                    <?php if (isset($item['client_url'])) : // Display chosen img ?>
                                        <a href="<?php echo (isset($item['client_url'])) ? $item['client_url'] : '' ?>" target="_blank">
											<span class="align-helper"></span>
											<img src="<?php echo $article_image ?>" alt="<?php echo (isset($item['main_title'])) ? $item['main_title'] : '' ?>" title="<?php echo (isset($item['main_title'])) ? $item['main_title'] : '' ?>"/>
										</a>
                                    <?php else : ?>
										<span class="align-helper"></span>
                                        <img src="<?php echo $article_image ?>" alt="<?php echo (isset($item['main_title'])) ? $item['main_title'] : ''; ?>" title="<?php echo (isset($item['main_title'])) ? $item['main_title'] : '' ?>"/>
                                    <?php endif; ?>

                                </li>

                            <?php endif;   endforeach; ?>

                    </ul>
                </div>
            </div>
        </div>
	
		<div class="description columns three">
        <?php if (isset($main_title)) { ?>

			<?php include(dirname(__FILE__).'/_title.php');?>

			<?php echo mvb_parse_content($description) ?>

			<a class="read-more" href="#">View all</a>

        <?php } else { ?>

			<div class="twelve columns">
				<?php echo mvb_parse_content($description) ?>
			</div>

        <?php } ?>
		</div>


    <?php endif; ?>

	<script type="text/javascript">
		jQuery(document).ready(function ($) {
			var eqSlides = function(){
				$('.clients-list-slider > li').equalHeights({container: 'ul'});
			};
			
			eqSlides(); $(window).load(eqSlides).resize(eqSlides);
			
			jQuery('#<?php echo $unique_id ?>').flexslider({
				selector: ".clients-list-slider > li",
				namespace: "clients-",          //{NEW} String: Prefix string attached to the class of every element generated by the plugin
				animation: "slide",
				animationLoop: true,
				direction: "horizontal",
				itemWidth: 210,                   //{NEW} Integer: Box-model width of individual carousel items, including horizontal borders and padding.
				itemMargin: 20,                  //{NEW} Integer: Margin between carousel items.
				minItems: 1,                    //{NEW} Integer: Minimum number of carousel items that should be visible. Items will resize fluidly when below this.
				maxItems: 4,
				// Autostart
				slideshow: <?php echo (!empty($slideshow))?'true':'false'; ?>,
				// Slideshow speed
				<?php if (!empty($slideshow_speed) && is_numeric($slideshow_speed)): ?>
					slideshowSpeed: <?php echo intval($slideshow_speed); ?>,
				<?php endif; ?>
				controlsContainer: ".clients-list",
				controlNav: false,               //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
				directionNav: true,           //Boolean: Create navigation for previous/next navigation? (true/false)
				prevText: "",                 //String: Set the text for the "previous" directionNav item
				nextText: ""
			});
		});
	</script>
</div>