<?php if (!empty($effects)) {
    $cr_effect = ' cr-animate-gen"  data-gen="'.$effects.'" data-gen-offset="bottom-in-view';
} else {
    $cr_effect ='';
}

# Addition CSS styles
$addition_css_styles = '';

if (!empty($css_styles)) {
	$addition_css_styles .= $css_styles;
}
if (!empty($addition_css_styles)) {
	$addition_css_styles = 'style="' . $addition_css_styles . '"';
}

$unique_id .= uniqid('mvbpc');

?>
<div class="module recent-block module-post-carousel <?php echo (!empty($css)) ? $css : ''; ?> <?php echo $cr_effect; ?>"  <?php echo $addition_css_styles; ?>>
    <?php include(dirname(__FILE__).'/_title.php'); ?>
	
	<div class="block-news-feature">
    <?php
    $the_query = null;
    $sticky = get_option('sticky_posts');

    if ($categories){
        $args = array(
            'category_name' => $categories,
            'posts_per_page' => $no_of_posts,
            'ignore_sticky_posts' => 1,
            'post__not_in' => $sticky,
        );
    } else {
        $args = array(
            'posts_per_page' => $no_of_posts,
            'ignore_sticky_posts' => 1,
            'post__not_in' => $sticky,
        );
    }

    $the_query = new WP_Query($args);
    echo '<div id="'. $unique_id .'" class="post-carousel-wrap"><ul class="post-carousel">';

    while ($the_query->have_posts()) : $the_query->the_post();

        $format = get_post_format();
        if (false === $format) {
            $format = 'standard';
        }

        $thumb = get_post_thumbnail_id();

        if (has_post_thumbnail()) {
            $img_url = wp_get_attachment_url($thumb, 'medium'); //get img URL
            $article_image = aq_resize($img_url, 580, 440, true);
        } else {
            $article_image = $no_image;
        } ?>

        <li class="post-carousel-item">
            <div class="item">
				<div class="entry-thumb">
					<img src="<?php echo $article_image; ?>" alt="" />
					<div class="entry-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></div>
					<div class="entry-meta"><i class="moon-tags-2"></i> <?php the_category(); ?></div>
					<a href="<?php the_permalink(); ?>" class="link"></a>
				</div>
            </div>
        </li>

    <?php

    endwhile;
    wp_reset_postdata();

    echo '</ul></div>';
    ?>
	</div>
	
    <script type="text/javascript">
        jQuery(document).ready(function () {

            var news_row = jQuery('#<?php echo $unique_id ?>');
            var item_width = news_row.width() / 2;

            jQuery('#<?php echo $unique_id ?>').flexslider({
                selector: ".post-carousel > li",
                namespace: "post-carousel-",          //{NEW} String: Prefix string attached to the class of every element generated by the plugin
                animation: "slide",
                direction: "horizontal",
                itemWidth: item_width-10,           //{NEW} Integer: Box-model width of individual carousel items, including horizontal borders and padding.
                itemMargin: 20,                  //{NEW} Integer: Margin between carousel items.
                minItems: 1,                    //{NEW} Integer: Minimum number of carousel items that should be visible. Items will resize fluidly when below this.
                maxItems: 2,
                slideshow: false,
                controlsContainer: news_row.find(".extra-links"),
                controlNav: false,               //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
                directionNav: true,           //Boolean: Create navigation for previous/next navigation? (true/false)
                prevText: "",                 //String: Set the text for the "previous" directionNav item
                nextText: "",
				start: function() {
					jQuery('#<?php echo $unique_id ?> .entry-thumb').each(function() {
						var img = jQuery(this).children('img');
						if (jQuery(this).height() < img.height()) {
							img.css({
								'margin-top': - (img.height() - jQuery(this).height()) / 2
							});
						}
						if (jQuery(this).height() > img.height()) {
							img.css({
								'margin-top': (jQuery(this).height() - img.height()) / 2
							});
						}
					});
				}
            });

        });
    </script>

</div>
